insert into EXERCICIO (ID_EXERCICIO, ID_EMPRESA, ANO, FECHADO)values (1, 1, 2010, 0);
insert into EXERCICIO (ID_EXERCICIO, ID_EMPRESA, ANO, FECHADO)values (2, 1, 2011, 0);
insert into EXERCICIO (ID_EXERCICIO, ID_EMPRESA, ANO, FECHADO)values (3, 1, 2012, 0);
insert into EXERCICIO (ID_EXERCICIO, ID_EMPRESA, ANO, FECHADO)values (4, 2, 2010, 0);